file_format: "1"
id: dasbob
name: Dasbob
type: shield
url: https://github.com/GroooveBob/DASBOB
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - dasbob_left
  - dasbob_right